apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: company-infra-finish:apps/Deployment:company-infra/nginx
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"company-infra-finish:apps/Deployment:company-infra/nginx"},"name":"nginx","namespace":"company-infra"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"nginx"}},"template":{"metadata":{"labels":{"app":"nginx"}},"spec":{"containers":[{"image":"nginx:latest","name":"nginx","ports":[{"containerPort":80}],"volumeMounts":[{"mountPath":"/etc/nginx/nginx.conf","name":"nginx-conf","subPath":"nginx.conf"},{"mountPath":"/usr/share/nginx/html","name":"webroot"}]}],"initContainers":[{"command":["sh","-c","echo \"\u003ch1\u003eWelcome to nginx!\u003c/h1\u003e\" \u003e /mnt/index.html"],"image":"busybox","name":"init-html","secuityContext":{"runAsUser":0},"volumeMounts":[{"mountPath":"/mnt","name":"webroot"}]}],"volumes":[{"configMap":{"name":"nginx-config"},"name":"nginx-conf"},{"name":"webroot","persistentVolumeClaim":{"claimName":"nginx-pvc"}}]}}}}
  creationTimestamp: "2025-07-07T12:35:46Z"
  generation: 1
  name: nginx
  namespace: company-infra
  resourceVersion: "329559"
  uid: b4225925-b426-4946-9634-7d40420620f6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: nginx-conf
          subPath: nginx.conf
        - mountPath: /usr/share/nginx/html
          name: webroot
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - echo "<h1>Welcome to nginx!</h1>" > /mnt/index.html
        image: busybox
        imagePullPolicy: Always
        name: init-html
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt
          name: webroot
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: nginx-config
        name: nginx-conf
      - name: webroot
        persistentVolumeClaim:
          claimName: nginx-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-07-07T12:35:56Z"
    lastUpdateTime: "2025-07-07T12:35:56Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-07-07T12:35:46Z"
    lastUpdateTime: "2025-07-07T12:35:56Z"
    message: ReplicaSet "nginx-5869cb6b8f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
