
prometheus:
  enabled: true
  nodePort: 30900
  storage: 1Gi
  config: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'mysqld-exporter'
        static_configs:
          - targets: ['mysqld-exporter:9104']
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter:9100']
      - job_name: 'nginx-exporter'
        static_configs:
          - targets: ['nginx-exporter:9113']

grafana:
  enabled: true
  nodePort: 30300
  storage: 1Gi

mysql:
  enabled: true
  nodePort: 30366
  rootPassword: "supersecret"
  database: "mydb"
  storage: 2Gi


nodeexporter:
  enabled: true
  nodePort: 31000

nginxexporter:
  enabled: true
  nodePort: 31113
  nginxScrapeUri: "http://nginx:80/stub_status"

jenkins:
  enabled: true
  storage: 2Gi
  nodePort: 30800

nginx:
  enabled: true
  nodePort: 30888
  config: |
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
      worker_connections 1024;
    }
    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      sendfile        on;
      keepalive_timeout  65;
      server {
        listen       80;
        server_name  localhost;
        location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
        }

        location /stub_status{
          stub_status;
          allow all;
          access_log off;
        }
      }
    }
  storage: 1Gi


apache2:
  enabled: true
  nodePort: 30880
  config: |
    ServerRoot "/usr/local/apache2"
    Listen 80
    LoadModule mpm_event_module modules/mod_mpm_event.so
    LoadModule unixd_module modules/mod_unixd.so
    LoadModule authz_core_module modules/mod_authz_core.so
    LoadModule authz_host_module modules/mod_authz_host.so
    ServerName localhost
    DocumentRoot "/usr/local/apache2/htdocs"
    <Directory "/usr/local/apache2/htdocs">
        Require all granted
    </Directory>
    ErrorLog /proc/self/fd/2
    LogLevel warn

ftp:
  enabled: true
  nodePort: 30210
  pasvPorts: [21100, 21101, 21102]
  config: |
    listen=YES
    anonymous_enable=NO
    local_enable=YES
    write_enable=YES
    pasv_enable=YES
    pasv_min_port=21100
    pasv_max_port=21102
    # 기타 vsftpd 설정
  storage: 1Gi

samba:
  enabled: true
  hostPath: /srv/samba-share
  nodePorts: [30139, 30445]
  storage: 1Gi
  config: |
    [share]
    path = /share
    read only = no
    browsable = yes
    guest ok = yes


rsnapbackup:
  enabled: true
  schedule: "0 2 * * *"
  config: |
    config_version__TAB__1.2
    sync_first__TAB__1
    cmd_cp__TAB__/bin/cp
    cmd_rm__TAB__/bin/rm
    cmd_rsync__TAB__/usr/bin/rsync
    cmd_logger__TAB__/usr/bin/logger
    snapshot_root__TAB__/backup/
    retain__TAB__daily__TAB__7
    retain__TAB__weekly__TAB__4
    retain__TAB__monthly__TAB__3
    backup__TAB__/data/__TAB__localhost/
  storage: 1Gi
  dataStorage: 1Gi


mysqldexporter:
  enabled: true
  nodePort: 31004

