{{- if .Values.rsnapbackup.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: rsnapbackup-config
  namespace: company-infra
data:
  rsnapshot.conf: |-
{{ .Values.rsnapbackup.config | replace "__TAB__" "\t" | nindent 4 }}
{{- end }}

