{{- if .Values.rsnapbackup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: rsnapbackup
  namespace: company-infra
spec:
  schedule: "{{ .Values.rsnapbackup.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: rsnapbackup
              image: ghcr.io/linuxserver/rsnapshot
              command:
                - /bin/sh
                - -c
                - "rsnapshot -c /config/rsnapshot.conf sync && rsnapshot -c /config/rsnapshot.conf daily"
              volumeMounts:
                - name: config
                  mountPath: /config/rsnapshot.conf
                  subPath: rsnapshot.conf
                - name: data
                  mountPath: /data
                - name: backup
                  mountPath: /backup
          volumes:
            - name: config
              configMap:
                name: rsnapbackup-config
            - name: data
              persistentVolumeClaim:
                claimName: data-pvc
            - name: backup
              persistentVolumeClaim:
                claimName: rsnapbackup-pvc
          restartPolicy: OnFailure
{{- end }}

